# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub - joshmurari'
        repository: 'joshmurari/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: ARM Template Deployment
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: Provisioning Container instance
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'ARM Connection'
        subscriptionId: '863894b0-b7e4-435a-8231-f817e50f3741'
        location: 'East US'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/joshmurari/azdevopsterraformlab/main/azuredeploy.json'
        overrideParameters: '-buildNumber $(tag)'
        deploymentMode: 'Incremental'